utilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix:   /

pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /

shop:
    resource: "@ShopBundle/Resources/config/routing.yml"
    prefix:   /shop
