produits:
    path:     /
    defaults: { _controller: ShopBundle:Produits:produits }

details:
    path:     /produit/{id}
    defaults: { _controller: ShopBundle:Produits:details }

categorieProduits:
    path:     /categorie/{categorie}
    defaults: { _controller: ShopBundle:Produits:categorie }

rechercheProduits:
    path:   /recherche
    defaults: { _controller: ShopBundle:Produits:rechercheTraitement }